name: Deploy Web Application To Any Environment By Dispatch Trigger
run-name: Dispatch Trigger Deploy [${{ github.event.client_payload.environmentName }}] Web Application  

on:
  repository_dispatch:
    types: [deploy-app-to-specific-environment]

permissions:
    id-token: write
    contents: read

env:
  DOTNET_VERSION: '6.x'
  AZURE_TENANT_ID:  ${{ secrets.AZURE_TENANT_ID }}

jobs:
  build-and-deploy-app-to-environment:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.client_payload.environmentName }}
    defaults:
      run:
        working-directory: ./app
        
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.APP_NAME }}
          slot-name: ${{ vars.SLOT_NAME }}
          package: ${{ env.DOTNET_ROOT }}/myapp